<?php
return [
    'id' => 'ID',
    'warranty' => 'Warranty:',
    'invoice' => 'Invoice:',
    'packaging' => 'Packaging:',
    'manual' => 'Manual:',
    'price' => 'Price:',
    'category_id' => 'Category:',
    'title' => 'Title:',
    'search_text' => 'Search text:',
    'user_id' => 'User id',
    'ad_type_id' => 'Ad type:',
    'description' => 'Description:',
    'price_min' => 'Min price:',
    'price_max' => 'Max price:',
    'created_at' => 'Created:',

    // Parsed data
    's_user' => 'User:',
    's_location' => 'Location:',
    's_phone' => 'Phone:',
    's_email' => 'Email:',
    's_adv' => 'Advertisement:',
    's_age' => 'Age:',
    's_date' => 'Post date:',
    's_warranty' => 'Warranty:',
    's_package' => 'Package:',
    's_delivery' => 'Delivery:',
    's_manual' => 'Manual:',
    's_akn' => 'Receipt:',
    's_expires' => 'Expires:',

    's_brand'       => 'Brand:',
    's_model'       => 'Model:',
    's_producer'    => 'Producer:',
    's_watt'        => 'Watt:',
    's_product'     => 'Product:',

    'media_title'       => 'Media title:',
    'media_genre'       => 'Genre:',
    'media_type'        => 'Type:',
    'media_producer'    => 'Producer:',

    'music_artist'      => 'Artist:',
    'media_features'    => 'Features:',
    'media_inches'      => 'Inches:',
    'media_size'        => 'Size:',
    'eq_capacity'       => 'Capacity(GB):',
    'hd_capacity'       => 'HD Capacity(GB):',
    'camera_resolution' => 'Resolution:',
    'optical_zoom'      => 'Optical zoom:',
    'speaker'           => 'Speaker:',
    'speaker_type'      => 'Speaker type:',
    'channels'          => 'Channels:',
];